apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-10-20T01:18:10Z"
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
  name: efs-csi-controller-sa
  namespace: kube-system
  resourceVersion: "42475"
  uid: 43d9d718-ca4f-4908-8fe8-6055eaece62b
  annotations:
   eks.amazonaws.com/role-arn: arn:aws:iam::411854276167:role/efs-csi
