apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-vol1
  labels:
    app: nginx
spec:
  accessModes:
  - ReadWriteOnce
  #storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
