# In Digital Ocean, create a pvc with a storage ClassName :do-block-storage and it will automatically create PV for you.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
