apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: app-pvc
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
     storage: 1Gi
  selector:
   matchLabels:
    vol: mysql
