apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Kenmakhanu/eks-argo.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      selfHeal: true
      prune: true