apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: my-nginx
    repoURL: git+https://github.com/Wemadevops/eks-argo@my-nginx?ref=main&sparse=0
    targetRevision: 0.1.0
    helm:
      releaseName: my-nginx
      values: |
        service:
          type: NodePort
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true